### ISSUE TITLE
Specify number of partition for producer

### ISSUE THREAD

**Issue by mavencode01** [cyngn/vertx-kafka#2]
Is there a way to specify the number of partition for the producer ?

I glanced through the documentation but it's not mentioned anywhere.

Thanks

**Comment by jtruelove** [comment]
We do not currently support this but we can take a look and see what it will take to add that in.

**Comment by jtruelove** [comment]
how does this look as far as an approach and meeting your needs, look at KafkaPublisher

http://review.cyanogenmod.org/120660

still needs testing but that's the basic idea

**Comment by jtruelove** [comment]
This is done let me know if you see issues.
