### ISSUE TITLE
Publish to multiple topic

### ISSUE THREAD

**Issue by mavencode01** [cyngn/vertx-kafka#3]
I think it would be nice to be able to publish to multiple topics in the same Verticle by specifying the
topic name when publishing a new message.

Any thought ?

**Comment by jtruelove** [comment]
Yeah that sounds totally reasonable, we can add that to the list.

**Comment by jtruelove** [comment]
how does this look as far as an approach and meeting your needs, look at KafkaPublisher

http://review.cyanogenmod.org/120660

still needs testing but that's the basic idea

**Comment by mavencode01** [comment]
@jtruelove this looks good!

Thanks again

**Comment by jtruelove** [comment]
I just published changes let me know if you see issues.
