### ISSUE TITLE
Error handling support

### ISSUE THREAD

**Issue by mavencode01** [cyngn/vertx-kafka#4]
I'm really considering using this in production but I've got one issue on how to handle an error if
my Kafka cluster is down for any reasons.

Is there a way you might return a response when a message is posted to the publisher address ?

for example 

```
vertx.eventBus().send(MessageProducer.EVENTBUS_DEFAULT_ADDRESS, json.toString(), response -> {
                    if (response.succeeded()){
                        LOG.info("Message queued successfully ::: {}", response.result().body());
                    }else{
                        LOG.error("Failed to queue message :::: {}", response.cause().getMessage());
                        response.cause().printStackTrace();
                    }
                });  
```

**Comment by jtruelove** [comment]
yeah i just added logging on the error in the publisher but i can add an option to supply an error callback

**Comment by jtruelove** [comment]
to keep things efficient i might just add a single event bus topic for errors that you can consume on

**Comment by mavencode01** [comment]
Yeah, that serves it right too.

**Comment by jtruelove** [comment]
you could still do the raw publishing how you are but the KafkaPublisher you see in that review just is a bit simpler/cleaner, so if you really want to look at every response you can OR say just listen for "Kafka.EventBus.Producer.Error" etc..

**Comment by mavencode01** [comment]
That makes sense...simpler/cleaner :8ball:

**Comment by jtruelove** [comment]
I've got all the changes in you requested, but I need to re-work the consumer a bit as the library has changed and broken the old code. It will take me a day or so probably to get that corrected and fixed and a new library published.

**Comment by mavencode01** [comment]
No worries, let me know how I can help.

Thanks

**Comment by mavencode01** [comment]
@jtruelove were you able to publish your changes ?

**Comment by jtruelove** [comment]
I just published, it will take a little bit to hit central. There were a bunch of breaking 0.9.0 changes on the consumer side I had to fix. Everything should be updated now let me know if you see any issues. This is fully using 0.9.0.0 on the client side.
